config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get "products/search" => "products#search", as: :search_product
  resources :products

  get "shops/search" => "shops#search", as: :search_shop
  resources :shops
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :title
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_and_belongs_to_many :shop, join_table: :shops_products
  
  validates_presence_of :title, :description, :category

  scope :with_title, -> (title) { where("products.title LIKE :title", { title: "%#{title}%" }) }
  scope :with_category, -> (category_id) { joins(:category).where(categories: { id: category_id }) }
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_and_belongs_to_many :product, join_table: :shops_products
  
  validates_presence_of :name, :description

  scope :with_name, -> (name) { where("name LIKE :name", { name: "%#{name}%" }) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def edit
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully saved." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully saved." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
    end
  end

  def search
    @products = Product.with_title(params[:title]).with_category(params[:category])
    render :index
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :category_id)
    end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
    @shops = Shop.all
  end

  def new
    @shop = Shop.new
  end

  def show
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: "Shop was successfully saved." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: "Shop was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
    end
  end

  def search
    @shops = Shop.with_name(params[:search])
    render :index
  end

  private

    def set_shop
      @shop = Shop.find(params[:id])
    end

    def shop_params
      params.require(:shop).permit(:name, :description, :product_ids => [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div>
    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @category do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to "Show", category %></td>
        <td><%= link_to "Edit", edit_category_path(category) %></td>
        <td><%= link_to "Destroy", category, method: :delete, data: { confirm: "Are you sure ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>Add Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %>
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<% if @product.errors.any? %>
  <div>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @product do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :category_id %>
    <%= collection_select(:product, :category_id, Category.all, :id, :title) %>
  </div>

  <div>
    <%= f.submit 'Save' %>
  </div>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<div>
  <%= form_tag(search_product_path, method: "get") do %>
    <%= label_tag :title, "Search:" %> <br>
    <%= text_field_tag :title, params[:title], placeholder: "Search Products" %>
    <%= select_tag :category, options_from_collection_for_select(Category.all, "id", "title", params[:category]) %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>

<table>
  <thead>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
  </thead>

  <tbody>
    <% @products.each do |product|%>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.category.title %></td>
        <td><%= link_to "Show", product %></td>
        <td><%= link_to "Edit", edit_product_path(product) %></td>
        <td><%= link_to "Destroy", product, method: :delete, data: { confirm: "Are you sure ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>Add Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Category:</strong>
  <%= @product.category.title %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %>
<%= link_to 'Back', products_path %>

app/views/shops/_form.html.erb
<% if @shop.errors.any? %>
  <div>
    <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @shop do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :product_id %>
    <%= collection_select(:shop, :product_ids, Product.all, :id, :title, { :selected => @shop.product_ids }, { multiple: true }) %>
  </div>

  <div>
    <%= f.submit 'Save' %>
  </div>

<% end %>

app/views/shops/edit.html.erb
<h1>Edit Shop</h1>

<%= render "form" %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shops</h1>

<div>
  <%= form_tag(search_shop_path, method: "get") do %>
    <%= label_tag :search, "Search by name:" %> <br>
    <%= text_field_tag :search, params[:search], placeholder: "Search Shops" %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>

<table>
  <thead>
    <th>Name</th>
    <th>Description</th>
    <th>Products</th>
  </thead>

  <tbody>
    <% @shops.each do |shop|%>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.description %></td>
        <td>
          <%= shop.product.size %>
        </td>
        <td><%= link_to "Show", shop %></td>
        <td><%= link_to "Edit", edit_shop_path(shop) %></td>
        <td><%= link_to "Destroy", shop, method: :delete, data: { confirm: "Are you sure ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>Add Shop</h1>

<%= render "form" %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>
<p>
  <strong>Products:</strong> <br>

  <ul>
    <% @shop.product.each do |p| %>
      <li>
        <%= p.title %>
      </li>
    <% end %>
  </ul>
  
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %>
<%= link_to 'Back', shops_path %>